### ISSUE TITLE
Npm/node fails on run-script serve

### ISSUE THREAD

**Issue by flacombe** [openinframap/web#19]
While improving package.json file, I find the following exception when starting in production mode :
```
> openinframap-web@1.0.0 serve /opt/oim-web
> node ./dist/server.js

/opt/oim-web/dist/server.js:1
(function (exports, require, module, __filename, __dirname) { !function(t){var e={};function r(i){if(e[i])return e[i].exports;var n=e[i]={i:i,l:!1,exports:{}};return t[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}r.m=t,r.c=e,r.d=function(t,e,i){r.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:i})},r.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},r.t=function(t,e){if(1&e&&(t=r(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var i=Object.create(null);if(r.r(i),Object.defineProperty(i,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var n in t)r.d(i,n,function(e){return t[e]}.bind(null,n));return i},r.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return r.d(e,"a",e),e},r.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},r.p="",r(r.s=21)}([function(t,e){var

ReferenceError: window is not defined
    at i (/opt/oim-web/dist/server.js:1:654468)
    at s (/opt/oim-web/dist/server.js:1:654556)
    at t.exports (/opt/oim-web/dist/server.js:1:658076)
    at Object.<anonymous> (/opt/oim-web/dist/server.js:1:659653)
    at r (/opt/oim-web/dist/server.js:1:172)
    at Module.<anonymous> (/opt/oim-web/dist/server.js:1:724123)
    at r (/opt/oim-web/dist/server.js:1:172)
    at /opt/oim-web/dist/server.js:1:964
    at Object.<anonymous> (/opt/oim-web/dist/server.js:1:974)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

Also, the following should be added to ./webpack.prod.js :

```
output: {
    filename: 'server.js',
    path: path.resolve(__dirname, 'dist'),
  }
```

All the best

**Comment by russss** [comment]
That serve command is not used, and was probably added in error at some point (perhaps because I copied the package.json from somewhere else).

In production I'm serving directly with nginx after running `npm run build`, as it's simply a static site.

I've removed that from the package.json.

**Comment by flacombe** [comment]
Could you please share your nginx config to serve directly with it ?
That would save me a node.js process

**Comment by russss** [comment]
```
server {
        listen <addr>:80;

        root /var/www/openinframap/dist;
        index index.html;

        server_name openinframap.org;
        gzip on;
        gzip_proxied any;
        gzip_types application/x-protobuf application/json application/javascript;

        location /tiles {
                if ($uri ~ "/tiles/[0-6]/") {
                        expires 24h;
                }
                if ($uri ~ "/tiles/[7-9]/") {
                        expires 6h;
                }
                if ($uri ~ "/tiles/(10|11|12|13|14|15|16)/") {
                        expires 30m;
                }
                proxy_pass http://127.0.0.1:8081/maps/openinframap;
        }

        location ~ \.json$ {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        }

        location ~ \.js$ {
                expires 30d;
        }

        location / {
                try_files $uri $uri/ =404;
        }
}
```

**Comment by flacombe** [comment]
Sounds really good, thank you

I've included it in the git repository and use a sym link to put it live in the nginx config. That save time on deploy.
